# fly.toml app configuration file generated for whisper-farm-worker on 2024-06-16T14:41:12+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whisper-farm-worker'
primary_region = 'ord'

[deploy]
  strategy = "immediate"

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'a100-40gb'
